# docker-compose.yml

version: "3"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dockervolumes/data:/data
      - ./dockervolumes/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - proxy-network

  dlrgweb:
    container_name: dlrgWeb
    #image: adjeko/dlrgtrack:latest
    build:
      context: .
    privileged: false
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - proxy-network
  
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    environment:
      ENCRYPTION: example #optional
    ports:
      - "8090:8090"
    volumes:
      - ./dockervolumes/pocketbase_data:/pb_data
      - ./dockervolumes/pocketbase_public:/pb_public #optional
    healthcheck: #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
