version: '3'
services:
  dlrgweb:
    container_name: dlrgWeb
    build: .
    privileged: false
    ports:
      - "3000:3000"
    # volumes:
  dlrgpocketbase:
    container_name: dlrgPocketbase
    build: ./pocketbase
    image: pocketbase:latest
    volumes:
      - pocketbase-volume:/app/data
    ports:
      - "8080:8080"

      
volumes:
  pocketbase-volume:
